### ISSUE TITLE
Requires non-ASDF stuff to build

### ISSUE THREAD

**Issue by quicklisp** [ryepup/cl-opencv#2]
It looks like this now requires some shell activity with a makefile to fully build cl-opencv. That means I can't build it into Quicklisp. Is there any chance of invoking the external stuff from within the ASDF system, like some other projects do?

**Comment by ryepup** [comment]
Is there a project you recommend that I can use as a example? clsql?

**Comment by quicklisp** [comment]
Not sure - CommonQt perhaps.

**Comment by ryepup** [comment]
Note to self: http://gitorious.org/commonqt/commonqt/blobs/master/qt.asd; defines a new `source-file` subclass and uses `asdf:run-shell-command` to do the compilation.
